# Generated by Django 2.2.5 on 2019-09-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0003_auto_20190907_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.Cotizacion'),
        ),
    ]
