# Generated by Django 2.2.5 on 2019-09-09 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0004_auto_20190908_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='orden_proveedor',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
