# Generated by Django 2.2.5 on 2019-09-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisiciones', '0009_reportecompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportecompras',
            name='requisicion',
        ),
        migrations.AlterField(
            model_name='reportecompras',
            name='estado_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.EstatusCompras'),
        ),
        migrations.CreateModel(
            name='CotizacionCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('folio', models.CharField(max_length=250)),
                ('monto', models.FloatField()),
                ('proveedores', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reportecompras',
            name='cotizacion_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.CotizacionCompras'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='cotizacion_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.CotizacionCompras'),
        ),
    ]
