# Generated by Django 2.2.5 on 2019-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0011_estatuscompras_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecompras',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
