# Generated by Django 2.2.5 on 2019-09-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0012_auto_20190923_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecompras',
            name='paqueteria',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
