# Generated by Django 2.2.5 on 2019-09-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0013_reportecompras_paqueteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecompras',
            name='cotizacion_compras',
        ),
        migrations.AddField(
            model_name='reportecompras',
            name='requisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.Requisicion'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='compra_rapida',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
