# Generated by Django 2.2.5 on 2019-09-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20190917_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='contacto',
            new_name='nombre_comercial',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='nombre_fiscal',
        ),
    ]
