# Generated by Django 2.2.5 on 2019-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20190917_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
